In [6]:
import requests
import datetime
from exec import execute_query

API's allow us to talk to other servers on the web. In this case, we can use the randomuser API to get randomized, mock user data. Run this command to get 50 users from the API.

In [7]:
results_number = int(input("How many users do you want?"))
response = requests.get(f"https://randomuser.me/api/?results={results_number}")
res = response.json()

Let's iterate over the random user data and store them in an array.

In [8]:
users = res["results"]

user_list = []

for u in users:
    user = {}
    user['username'] = u["login"]["username"]
    user['first_name'] = u["name"]["first"]
    user['last_name'] = u["name"]["last"]
    user['phone'] = u["phone"]
    user['birthday'] = u["dob"]["date"]
    user['age'] = u["dob"]["age"]
    user['created_at'] = datetime.datetime.now()

    # Add each dictionary to our array.
    user_list.append(user)

Let's add these users to the database by looping over them and adding them to the database one by one.

In [9]:
for user in user_list:
    # construct query string to create a user
    user_query_string = f"""INSERT INTO users (
                            username, 
                            first_name, 
                            last_name, 
                            phone, 
                            birthday, 
                            age, 
                            created_at
                        ) VALUES (
                            '{user['username']}', 
                            '{user['first_name']}', 
                            '{user['last_name']}', 
                            '{user['phone']}', 
                            '{user['birthday']}', 
                            {int(user['age'])}, 
                            CURRENT_TIMESTAMP
                        );"""

    # Run query to create each user
    execute_query(user_query_string)

DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'orangelion708',
                            'Antonio',
                            'Moya',
                            '931-720-703',
                            '1989-04-19T10:50:33.022Z',
                            33,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'silvergorilla956',
                            'Melisa',
                            'Roger',
                            '077 243 33 55',
                            '1984-01-17T19:30:06.394Z',
                            38,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'blacktiger126',
                            'Xavier',
                            'Bouchard',
                            'L22 A18-7864',
                            '1982-09-17T10:25:53.552Z',
                            39,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'angrygorilla101',
                            'Hotina',
                            'Oliynik',
                            '(068) C55-6613',
                            '1948-05-01T04:10:00.289Z',
                            74,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'heavybutterfly198',
                            'Klara',
                            'Hussein',
                            '51816054',
                            '1973-12-09T15:11:26.095Z',
                            48,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'greenpeacock735',
                            'Adem',
                            'Tokatlıoğlu',
                            '(708)-122-3350',
                            '1960-04-27T23:49:43.727Z',
                            62,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'heavymouse710',
                            'Dan',
                            'Morris',
                            '06-4898-7582',
                            '1986-08-24T12:31:51.190Z',
                            35,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'happybird307',
                            'Jens',
                            'Blanc',
                            '076 784 35 88',
                            '1970-02-12T11:33:50.789Z',
                            52,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'heavygorilla171',
                            'Caroline',
                            'Sørensen',
                            '91797507',
                            '1949-08-08T22:19:02.765Z',
                            72,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'ticklishbear988',
                            'Theo',
                            'Gerard',
                            '078 796 07 27',
                            '1953-08-08T04:47:23.913Z',
                            68,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'bluewolf386',
                            'Godofredo',
                            'Lopes',
                            '(24) 1106-9769',
                            '1987-03-30T00:02:13.601Z',
                            35,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'yellowgoose843',
                            'Lucy',
                            'Hunter',
                            '051-356-5049',
                            '1981-09-02T11:14:18.170Z',
                            40,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'greenduck184',
                            'Cecil',
                            'Taylor',
                            '06-9981-9656',
                            '1963-10-28T00:36:09.349Z',
                            58,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'organicostrich730',
                            'Fabien',
                            'Gerard',
                            '01-35-05-27-61',
                            '1992-01-26T21:11:13.404Z',
                            30,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'orangebear692',
                            'Agathe',
                            'Michel',
                            '04-32-81-67-93',
                            '1963-12-07T00:28:55.640Z',
                            58,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'yellowleopard267',
                            'Armand',
                            'Legrand',
                            '05-74-50-72-52',
                            '1951-04-30T21:32:23.190Z',
                            71,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'bluegorilla407',
                            'Abigail',
                            'Lewis',
                            '(448)-288-3968',
                            '1988-06-28T13:30:05.359Z',
                            34,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'purpleswan507',
                            'Jeanette',
                            'Lawrence',
                            '03-9440-0845',
                            '1970-04-23T10:24:47.680Z',
                            52,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'angrybear498',
                            'Mina',
                            'Legrand',
                            '079 382 46 54',
                            '2001-04-29T20:12:39.290Z',
                            21,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'ticklishtiger575',
                            'Matthew',
                            'Hovin',
                            '37824294',
                            '1975-10-10T03:26:50.962Z',
                            46,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'crazybutterfly898',
                            'Dana',
                            'Zagaykevich',
                            '(097) K96-6881',
                            '1991-03-19T09:36:58.398Z',
                            31,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'whitetiger227',
                            'Consuelo',
                            'Nieto',
                            '958-440-299',
                            '1951-12-21T03:32:24.877Z',
                            70,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'crazydog869',
                            'Chloe',
                            'Chen',
                            '(098)-204-8059',
                            '1951-11-02T19:57:21.572Z',
                            70,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'smallrabbit406',
                            'Ostoja',
                            'Stojković',
                            '037-8682-429',
                            '1991-04-28T17:49:30.945Z',
                            31,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'happycat284',
                            'Gerardo',
                            'Stern',
                            '(0885) 123425',
                            '1999-10-06T05:01:51.901Z',
                            22,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'whitebear175',
                            'Éric',
                            'Chevalier',
                            '075 517 73 56',
                            '1995-06-30T10:14:12.999Z',
                            27,
                            CURRENT_TIMESTAMP
                        );
DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  INSERT INTO users (
                            username,
                            first_name,
                            last_name,
                            phone,
                            birthday,
                            age,
                            created_at
                        ) VALUES (
                            'heavybird385',
                            'Sahana',
                            'Kumar',

#### That created a number of new users and stored them in our database. We can test this by executing a SELECT query.

In [5]:
users_query = "SELECT * FROM users;"

users = execute_query(users_query)
user_count = 0
for user in users:
    user_count += 1

print("Number of users in database: ", user_count)

DB_CONNECTION_STRING postgresql+psycopg2://postgres:abcde12345@localhost:5432/fitter
running command:  SELECT * FROM users;
Number of users in database:  51